// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyLa1MOAGCs1-u0m8GHmpa0hUFvhlhvcM',
    appId: '1:28720548519:web:f97871435a980df10fa982',
    messagingSenderId: '28720548519',
    projectId: 'sanberapp61',
    authDomain: 'sanberapp61.firebaseapp.com',
    storageBucket: 'sanberapp61.firebasestorage.app',
    measurementId: 'G-7V6JKR2G0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBePxoexrf3ZahiJbncNUPAv7vfUoXaJ5s',
    appId: '1:28720548519:android:db2c156dfe3272d10fa982',
    messagingSenderId: '28720548519',
    projectId: 'sanberapp61',
    storageBucket: 'sanberapp61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrdRPHusUZ02FIO6jlFNhIwSsaZMhWdCw',
    appId: '1:28720548519:ios:d0c3e1c3fb3f9ae90fa982',
    messagingSenderId: '28720548519',
    projectId: 'sanberapp61',
    storageBucket: 'sanberapp61.firebasestorage.app',
    iosBundleId: 'com.example.sanberapp61',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrdRPHusUZ02FIO6jlFNhIwSsaZMhWdCw',
    appId: '1:28720548519:ios:d0c3e1c3fb3f9ae90fa982',
    messagingSenderId: '28720548519',
    projectId: 'sanberapp61',
    storageBucket: 'sanberapp61.firebasestorage.app',
    iosBundleId: 'com.example.sanberapp61',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyLa1MOAGCs1-u0m8GHmpa0hUFvhlhvcM',
    appId: '1:28720548519:web:cac0f2b6f3d5813c0fa982',
    messagingSenderId: '28720548519',
    projectId: 'sanberapp61',
    authDomain: 'sanberapp61.firebaseapp.com',
    storageBucket: 'sanberapp61.firebasestorage.app',
    measurementId: 'G-SZ1N5JQ2N8',
  );
}
